language: java
jdk: oraclejdk11

install: true
script: ./mvnw clean install

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.m2

before_script:
  - wget https://github.com/IMSGlobal/caliper-spec/archive/develop.zip
  - unzip develop.zip -d ..
  - mkdir -p src/test/resources/fixtures
  - mv ../caliper-spec-develop/fixtures/v1p1 src/test/resources/fixtures
  - mv ../caliper-spec-develop/fixtures/v1p2 src/test/resources/fixtures