language: java
jdk: openjdk11
dist: xenial

cache:
  directories:
    - "$HOME/.m2"

install: "git clone https://github.com/IMSGlobal/caliper-common-fixtures.git $HOME/caliper-common-fixtures && ln -s $HOME/caliper-common-fixtures/src/test/resources/ src/test/resources"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -DaltDeploymentRepository=io.cloudrepo::default::https://weldnorthanalytics.mycloudrepo.io/repositories/doolittle deploy"
  skip_cleanup: true
  on:
    branch: master
