language: java

cache:
  directories:
    - "$HOME/.m2"

install: "git clone https://github.com/IMSGlobal/caliper-common-fixtures.git $HOME/caliper-common-fixtures && ln -s $HOME/caliper-common-fixtures/src/test/resources/ src/test/resources"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -DaltDeploymentRepository=packagecloud-weldnorthanalytics::default::packagecloud+https://packagecloud.io/weldnorthanalytics/doolittle deploy"
  skip_cleanup: true
  on:
    branch: master
